name: Build project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RPIGREEN: /home/rin/actions-runner/_work/socials-backend/socials-backend/target/debug/social-tasks
  SLAVEGREEN: /home/rin/actions-runner/_work/socials-backend/socials-backend/target/debug/social-tasks

jobs:
  build-rpi-green:

    runs-on: rpi-green
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Stop service
      run: sudo systemctl stop social-tasks
    - name: Build debug
      run: cargo build

  restart-tasks-rpi-green:
    needs: build-rpi-green
    runs-on: rpi-green
    steps:
    - name: Replace fresh bin
      run: sudo cp -f $RPIGREEN /usr/bin/social-tasks
    - name: Restart service
      run: sudo systemctl restart social-tasks

  build-slave-green:
    runs-on: slave-green
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Stop service
      run: sudo systemctl stop social-tasks
    - name: Build debug
      run: cargo build

  restart-tasks-slave-green:
    needs: build-slave-green
    runs-on: slave-green
    steps:
    - name: Replace fresh bin
      run: sudo cp -f $SLAVEGREEN /usr/bin/social-tasks
    - name: Restart service
      run: sudo systemctl restart social-tasks
