name: Build project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rpi-green:

    runs-on: rpi-green
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Build debug
      run: cargo build

  restart-tasks-rpi-green:
    needs: build-rpi-green
    runs-on: rpi-green
    - name: Restart service
      run: sudo systemctl restart social-tasks

  build-slave-green:
    runs-on: slave-green
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Build debug
      run: cargo build

  restart-tasks-slave-green:
    needs: build-slave-green
    runs-on: slave-green
    - name: Restart service
      run: sudo systemctl restart social-tasks
