name: Build project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: social-runner

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Build debug
      run: cargo build
